name: CI/CD
on: push
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "App Built"
      
  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
  deploy:
    needs: [build, security]
    runs-on: ubuntu-latest
    steps:
      - run: echo "App Deployed"
