name: CI/CD
on: push
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "App Built"
      
  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
  deploy:
    needs: [build, security]
    runs-on: ubuntu-latest
    steps:
      - run: echo "App Deployed"
