name: CI/CD
on: push
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "App Built"
      
  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Run Snyk to check for vulnerabilities
        id: snyk-check
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true # To make sure that SARIF upload gets called
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        if: steps.snyk-check.outcome == 'failure' && steps.snyk-check.conclusion == 'success'
        with:
          sarif_file: snyk.sarif
      - name: Fail pipeline
        if: steps.snyk-check.outcome == 'failure' && steps.snyk-check.conclusion == 'success' && steps.upload-sarif.outcome == 'success'
        run: |
          echo "::error::Snyk found issues! Go to GitHub Code Scanning to view the issues."
          exit 1
       
  deploy:
    needs: [build, security]
    runs-on: ubuntu-latest
    steps:
      - run: echo "App Deployed"
